### ISSUE TITLE
Category color included in category entity

### ISSUE THREAD

**Issue by FieryCod** [knit-pk/api-v1-php#121]
Since the category widget required the color of the category to be shown then we would highly appreciate if you could add hex color to every category.
Thanks in advance.

**Comment by k911** [comment]
@knit-pk/seo Should we name the field `overlayColor`? Or It would be better to add it on Image entity?

**Comment by k911** [comment]
@knit-pk/seo ping

**Comment by FieryCod** [comment]
I would stick to ‘overlayColor’
