### ISSUE TITLE
Description does not have character limit

### ISSUE THREAD

**Issue by FieryCod** [knit-pk/api-v1-php#27]
Now description is not limited, but we should limit the length of description in an Article entity to 100 characters. Of course we can limit the description on the front but it will not look good with the rest of a page.

To conclude description in Article entity should be limited to 100 characters

**Comment by k911** [comment]
Actually, Article's description is now limited to 300 characters, and title to 100 characters.

https://github.com/knit-pk/api-v1-php/blob/72a2c523cabb6e03bab20481d1e1e073396b14f6/src/Entity/Article.php#L171

@FieryCod Could you confirm, that it works?

**Comment by k911** [comment]
Closing as invalid.

![screenshot_20180118_221516](https://user-images.githubusercontent.com/10072889/35121854-3047a94c-fc9d-11e7-80c9-575455048a43.png)

**Comment by FieryCod** [comment]
Please change then description to max 100 characters. We would highly appreciate it @k911 .
