### ISSUE TITLE
Database does not respects the time of creation

### ISSUE THREAD

**Issue by FieryCod** [knit-pk/api-v1-php#28]
In every deploy you made you did not add proper createdAt, updatedAt, publishedAt properties to entities. That is why it's hard for us to test new features on the front.
It is crucial for us.

**Comment by k911** [comment]
That's actually proper a behaviour. Every entity is re-generated at time of deploy, so it's created/upadatedAt attributes are the same. Once we skip development mode (first stable version), we'll have to use migrations and keep database not purged every deploy, to stay consistent.
